language: python
python: "3.7.3"
env:
  - DEV_PROGRA= "Daniel Hernández"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python soup.py